//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 09:52:41 PM CET 
//

package com.example.xmlScientificPublicationEditor.model.person;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.xmlScientificPublicationEditor.model.Person package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Person_QNAME = new QName("http://www.uns.ac.rs/Tim1", "person");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.xmlScientificPublicationEditor.model.Person
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAuthPerson }
     * 
     */
    public TAuthPerson createTAuthPerson() {
        return new TAuthPerson();
    }

    /**
     * Create an instance of {@link TPerson }
     * 
     */
    public TPerson createTPerson() {
        return new TPerson();
    }

    /**
     * Create an instance of {@link TAddress }
     * 
     */
    public TAddress createTAddress() {
        return new TAddress();
    }

    /**
     * Create an instance of {@link TInstitution }
     * 
     */
    public TInstitution createTInstitution() {
        return new TInstitution();
    }

    /**
     * Create an instance of {@link TAuthPerson.Roles }
     * 
     */
    public TAuthPerson.Roles createTAuthPersonRoles() {
        return new TAuthPerson.Roles();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPerson }{@code >}}
     * 
     */
    // @XmlElementDecl(namespace = "http://www.uns.ac.rs/Tim1", name = "person")
    // public JAXBElement<TPerson> createPerson(TPerson value) {
    //     return new JAXBElement<TPerson>(_Person_QNAME, TPerson.class, null, value);
    // }

}
