//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 09:52:41 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uns.ac.rs/Tim1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.xmlScientificPublicationEditor.model.person;
