//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 09:52:41 PM CET 
//


package com.example.xmlScientificPublicationEditor.model.person;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRole.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRole">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="user"/>
 *     &lt;enumeration value="reviewer"/>
 *     &lt;enumeration value="redactor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TRole")
@XmlEnum
public enum TRole {

    @XmlEnumValue("user")
    USER("user"),
    @XmlEnumValue("reviewer")
    REVIEWER("reviewer"),
    @XmlEnumValue("redactor")
    REDACTOR("redactor");
    private final String value;

    TRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRole fromValue(String v) {
        for (TRole c: TRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
